### ISSUE TITLE
Output export

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/works-magnet#55]
In an "Export publications" dropdown button, propose
- Export in csv (same columns as in displayed table)
- Export in jsonl (all the underlying data)
- Custom export for local BSO (.csv)

In an "Export datasets" dropdown button, propose
- Export in csv (same columns as in displayed table)
- Export in jsonl (all the underlying data)

Exported filename shoud be explicit, like
works_finder_publications_HASH_YYYY1_YYYY2_timestamp (.csv / .jsonl / _bso.csv)
where HASH is a hash of the query ?

**Comment by ericjeangirard** [comment]
csv not always valid for datasets
[works_finder_datasets_198131042_2016_2023_1707307768945.csv](https://github.com/dataesr/works-finder/files/14193624/works_finder_datasets_198131042_2016_2023_1707307768945.csv)
==> `ParserError: Error tokenizing data. C error: Expected 7 fields in line 144, saw 8`

**Comment by annelhote** [comment]
To test title error for DOI 10.5281/zenodo.1196303 and 10.57745/z4rpdk, use this query https://works-magnet.dataesr.ovh/?affiliations=universit%C3%A9+de+lorraine&datasets=true&endYear=2024&startYear=2010&view=datasets then choose tab "List of datasets" and export datasets in CSV (minimal data).
