### ISSUE TITLE
Suggestion de recherche à partir de RoR : noms d'affiliations

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/works-magnet#61]
(en français pour faciliter la discussion)

Cas d'usage: l'utilisateur a un (ou plusieurs ?) RoR pour un établissement ou labo

Le works-finder propose (dans un premier temps impose ?) une recherche avec 
- tous les labels disponibles dans RoR (nom, alias, acronymes dans les différentes langues) pour le RoR en entrée
- même chose avec tous les RoR "enfants".
==> par ex, pour le cas de l'UL, ca ferait une recherche équivalente à [ceci](https://works-finder.staging.dataesr.ovh/#/?affiliations=Universit%C3%A9+de+Lorraine&affiliations=University+of+Lorraine&affiliations=Animal+and+Functionality+of+Animal+Products&affiliations=Animal+et+Fonctionnalit%C3%A9s+des+Produits+Animaux&affiliations=Archives+Henri-Poincar%C3%A9+-+Philosophie+et+Recherches+sur+les+Sciences+et+les+Technologies&affiliations=Bureau+for+Economic+Theory+and+Applications&affiliations=Bureau+d'Economie+Th%C3%A9orique+et+Appliqu%C3%A9e&affiliations=Centre+d'Investigation+Clinique+Pierre+Drouin&affiliations=CIC-Pierre+Drouin&affiliations=CIC-P+NANCY&affiliations=Centre+de+Recherches+P%C3%A9trographiques+et+G%C3%A9ochimiques&affiliations=Computer+Processing+and+Analysis+of+the+French+Language&affiliations=Analyse+et+Traitement+Informatique+de+la+Langue+Fran%C3%A7aise&affiliations=Diagnosis+and+International+Adaptive+Imaging&affiliations=IADI+Lab&affiliations=Imagerie+Adaptative+Diagnostique+et+Interventionnelle&affiliations=Dynamique+des+G%C3%A9nomes+et+Adaptation+Microbienne&affiliations=DynAMic&affiliations=Georgia+Tech-CNRS+Laboratory&affiliations=Groupe+de+Recherche+en+%C3%89nergie+%C3%89lectrique+de+Nancy&affiliations=Ing%C3%A9nierie+Mol%C3%A9culaire+et+Physiopathologie+Articulaire&affiliations=Institut+Jean+Lamour&affiliations=Institut+%C3%89lie+Cartan+de+Lorraine&affiliations=Institut+%C3%89lie-Cartan+de+Nancy&affiliations=Institute+for+Social+Sciences+and+Humanities&affiliations=Maison+des+Sciences+de+l'Homme&affiliations=Interactions+Arbres-Microorganismes&affiliations=Interdisciplinary+Laboratory+for+Continental+Environments&affiliations=Laboratoire+Interdisciplinaire+des+Environnements+Continentaux&affiliations=Labex+ARBRE&affiliations=Advanced+Research+on+the+Biology+of+Tree+and+Forest+Ecosystems&affiliations=Laboratory+of+Excellence+for+Advanced+Research+on+the+Biology+of+TRee+and+Forest+Ecosystems&affiliations=Laboratoire+Mat%C3%A9riaux+Optiques+Photonique+et+Syst%C3%A8mes&affiliations=Laboratoire+R%C3%A9actions+et+G%C3%A9nie+des+Proc%C3%A9d%C3%A9s&affiliations=Laboratoire+d'Energ%C3%A9tique+et+de+M%C3%A9canique+Th%C3%A9orique+et+Appliqu%C3%A9e&affiliations=Laboratoire+de+Chimie+Physique+et+Microbiologie+pour+l'Environnement&affiliations=Laboratoire+de+Conception+Fabrication+Commande&affiliations=Laboratory+of+design+manufacturing+and+control&affiliations=Laboratoire+de+Cristallographie+R%C3%A9sonance+Magn%C3%A9tique+et+Mod%C3%A9lisations&affiliations=Laboratory+of+Crystallography+Nuclear+Magnetic+Resonance+and+Modelling&affiliations=Crystallography+Magnetic+Resonance+and+Modeling+Laboratory&affiliations=Labor+f%C3%BCr+Kristallographie+Kernspinresonanz+und+Modellierung&affiliations=Laboratory+of+Microstructure+Studies+and+Mechanics+of+Materials&affiliations=Laboratoire+d'%C3%89tude+des+Microstructures+et+de+M%C3%A9canique+des+Mat%C3%A9riaux&affiliations=Laboratory+of+Soil+and+Environmental+Sciences&affiliations=Laboratoire+Sols+et+Environnement&affiliations=Lorraine+Research+Laboratory+in+Computer+Science+and+its+Applications&affiliations=Laboratoire+Lorrain+de+Recherche+en+Informatique+et+ses+Applications&affiliations=Research+Center+for+Automatic+Control+of+Nancy&affiliations=Centre+de+Recherche+en+Automatique+de+Nancy&affiliations=Silva&affiliations=Zone+Atelier+Moselle&affiliations=Centre+Europ%C3%A9en+de+Recherche+en+Economie+Financi%C3%A8re+et+Gestion+des+Entreprises&affiliations=European+Center+for+Research+in+Financial+Economics+and+Business+Management&affiliations=Europ%C3%A4ische+Zentrum+f%C3%BCr+Forschung+in+Finanz%C3%B6konomie+und+Unternehmensf%C3%BChrung&affiliations=Centro+Europeo+de+Investigaci%C3%B3n+en+Econom%C3%ADa+Financiera+y+Gesti%C3%B3n+Empresaria&affiliations=Laboratoire+Interuniversitaire+des+Sciences+de+l'Education+et+de+la+Communication&affiliations=Laboratoire+de+G%C3%A9nie+Informatique+de+Production+et+de+Maintenance&affiliations=Laboratoire+Agronomie+et+Environnement&affiliations=GeoRessources&affiliations=Observatoire+Terre+et+environnement+de+Lorraine&affiliations=Laboratoire+de+Chimie-Physique+Macromol%C3%A9culaire&affiliations=Laboratoire+Lorrain+de+Chimie+Mol%C3%A9culaire&affiliations=Laboratoire+de+Physique+et+Chimie+Th%C3%A9oriques&affiliations=Centre+de+Recherche+sur+les+M%C3%A9diations&affiliations=Centre+de+recherche+sur+les+m%C3%A9diations+(Crem)&affiliations=Laboratoire+d'Ing%C3%A9nierie+des+Biomol%C3%A9cules&affiliations=Laboratory+of+Biomolecules+Engineering&affiliations=LIBio&affiliations=Biomolecular+Engineering+Laboratory&affiliations=Laboratoire+de+Conception+Optimisation+et+Mod%C3%A9lisation+des+Syst%C3%A8mes&affiliations=Laboratoire+LCOMS&affiliations=Cibles+th%C3%A9rapeutiques+formulation+et+expertise+pr%C3%A9clinique+du+m%C3%A9dicament&affiliations=Therapeutic+Targets+Formulation+and+Preclinical+Expertise+of+Pharmaceuticals&affiliations=D%C3%A9faillance+Cardiovasculaire+Aigu%C3%AB+et+Chronique&affiliations=Acute+and+Chronic+Cardiovascular+Deficiency&affiliations=D%C3%A9veloppement+Adaptation+et+Handicap&affiliations=Development+Adaptation+and+Handicap&affiliations=DevAH&affiliations=Interactions+G%C3%A8ne-Environnement+en+Physiopathologie+Cardio-Vasculaire&affiliations=Gene-Environnement+Interactions+in+Cardio-Vascular+Physiopathology&affiliations=Nutrition-G%C3%A9n%C3%A9tique+et+Exposition+aux+Risques+Environnementaux&affiliations=Nutrition-Genetics+and+Exposure+to+Environmental+Risks&affiliations=Stress+immunit%C3%A9+pathog%C3%A8nes&affiliations=Laboratoire+SIMPA&affiliations=Stress+Immunity+Pathogens&affiliations=Interpsy&affiliations=InterPsy+Laboratory&affiliations=Laboratoire+InterPsy&affiliations=Psychologie+Ergonomique+et+Sociale+pour+l'Exp%C3%A9rience+Utilisateurs&affiliations=Laboratoire+de+Chimie+et+Physique+-+Approche+Multi-%C3%A9chelle+des+Milieux+Complexes&affiliations=Compos%C3%A9s+Alimentaires+:+Biofonctionnalit%C3%A9s+et+risques+Neurotoxiques&affiliations=Food+Compounds:+Biofunctionalities+and+Neurotoxic+Risks&affiliations=Calbinotox&affiliations=%C3%89quipe+de+Recherche+sur+les+Processus+Innovatifs&affiliations=Research+Team+on+Innovation+Process&affiliations=Laboratoire+d'Etude+et+de+Recherche+sur+le+Mat%C3%A9riau+Bois&affiliations=Institut+Fran%C3%A7ois+G%C3%A9ny&affiliations=Fran%C3%A7ois+G%C3%A9ny+Institute&affiliations=Institut+de+recherches+sur+l'%C3%A9volution+de+la+nation+et+de+l'%C3%89tat&affiliations=Centre+d'Etudes+Germaniques+Interculturelles+de+Lorraine&affiliations=Centre+de+Recherche+sur+les+Cultures+et+les+Litt%C3%A9ratures+Europ%C3%A9ennes&affiliations=Centre+de+Recherche+en+G%C3%A9ographie&affiliations=Centre+de+Recherche+Universitaire+Lorrain+d%E2%80%99Histoire&affiliations=Centre+lorrain+de+recherches+interdisciplinaires+dans+les+domaines+des+litt%C3%A9ratures+des+cultures+et+de+la+th%C3%A9ologie&affiliations=Centre+de+recherche+%C3%89critures&affiliations=Centre+%C3%89critures&affiliations=Histoire+et+Cultures+de+l'Antiquit%C3%A9+et+du+Moyen+%C3%82ge&affiliations=Interdisciplinarit%C3%A9+dans+les+Etudes+Anglophones&affiliations=Interdisciplinarity+in+English+Studies&affiliations=Litt%C3%A9ratures+Imaginaire+Soci%C3%A9t%C3%A9s&affiliations=Centre+de+recherches+Litt%C3%A9ratures+Imaginaire+Soci%C3%A9t%C3%A9s&affiliations=Laboratoire+Lorrain+de+Sciences+Sociales&affiliations=Laboratoire+lorrain+de+psychologie+et+neurosciences+de+la+dynamique+des+comportements&affiliations=Micropesanteur+Fondamentale+et+Appliqu%C3%A9e&affiliations=Fundamental+and+Applied+Microgravity&affiliations=GDR+Micropesanteur+Fondamentale+et+Appliqu%C3%A9e&affiliations=Groupement+de+Recherche+Micropesanteur+Fondamentale+et+Appliqu%C3%A9e&affiliations=Groupement+de+Recherche+Fundamental+and+Applied+Microgravity&affiliations=F%C3%A9d%C3%A9ration+de+Recherche+Spectroscopies+de+Photo%C3%A9mission&affiliations=Spectroscopies+de+Photo%C3%A9mission&affiliations=GDR+NBODY+:+Probl%C3%A8me+quantique+%C3%A0+N+corps+en+chimie+et+physique&affiliations=Groupement+de+Recherche+NBODY:+Quantum+n-body+problem+in+chemistry+and+physics&affiliations=Groupement+de+Recherche+:+Probl%C3%A8me+quantique+%C3%A0+N+corps+en+chimie+et+physique&affiliations=GDR+NBODY:+Quantum+n-body+problem+in+chemistry+and+physics&affiliations=F%C3%A9d%C3%A9ration+de+Recherche+sur+l'Energie+Solaire&affiliations=F%C3%A9dESol&affiliations=INFRANALYTICS&affiliations=FR+2054&affiliations=Microscopie+Fonctionnelle+du+Vivant&affiliations=Biophotonique+Microscopie+Fonctionnelle+du+Vivant&affiliations=GDR+Microscopie+Fonctionnelle+du+Vivant&affiliations=Groupement+de+Recherche+Microscopie+Fonctionnelle+du+Vivant&datasets=true&endYear=2023&startYear=2021) sans pour autant que tous les labels s'affichent. En terme d'interface, à voir comment l'utilisateur pourra ajouter / amender cette liste.

**Comment by hbretel** [comment]
Dans une certaine mesure, ce cas d'usage pourrait être élargi à tous les référentiels de structures ouverts qui permettent d'interroger des hiérarchies et de renvoyer des noms et variantes, en particulier AuréHAL je pense.
