### ISSUE TITLE
Bulk edit feature for the openalex use case

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/works-magnet#67]
The idea would be allow the user to select (need checkbox for each line) one or multiple lines, and 
- click a button to add a ror (the same to all lines) to each one of them [error message if the ror is already in one of lines]
- click another button to remove a ror (the same) to each of them [error message if the ror is not in one of lines]

**Comment by annelhote** [comment]
1. Add feature to select 1 or multiples lines
2. Add action box to the left
3. Bulk actions should be "Add RoR" or "Delete RoR"
4. On click on action button, open a pop up to choose the RoR to add / delete
5. Run
