### ISSUE TITLE
Potential bug or limit: 40 of 135 corrections were transferred to dataesr/openalex-affiliations.

### ISSUE THREAD

**Issue by koenbokern** [dataesr/works-magnet#71]
I tried to add 135 corrections related to the keyword 'Aeres' on 22-07-2024.
Only 40 were transferred to https://github.com/dataesr/openalex-affiliations/issues.
Is this a bug or an export/import limit?

The .csv file has been attached to this issue.
[works_magnet_OpenAlexerrors_1721669408555_2010_2024_2240186876.csv](https://github.com/user-attachments/files/16867584/works_magnet_OpenAlexerrors_1721669408555_2010_2024_2240186876.csv)

**Comment by annelhote** [comment]
It seems like we reached a rate limit https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#about-secondary-rate-limits. Thanks for letting us know that issue. WIP

**Comment by koenbokern** [comment]
@annelhote Could this rate limit issue also have led to a ban for my work email address? Today I was only able to add new corrections using a personal email address after multiple tries with my work address that I used in July. My public work adress is listed on my profile.

I don't mind using a personal address, but if ROR were to add mail domains to their registry, and you could log into WorksMagnet using ORCID ID with mail domain trust markers that WorksMagnet can read, then WorksMagnet could solely accept corrections for the user's organization or from users with any verified domain. Then I would like to use my work email adress again.

I have now added all corrections I wanted to make at this moment and I am curious about the results shown in a future OpenAlex database update.

**Comment by koenbokern** [comment]
WorksMagnet only started to (almost instantaneously) add corrections to GitHub after using a different email address after repeated tries in the hour before (since I did not know what to expect and I still had the tab open). I did not see an error, nor any confirmation.
