### ISSUE TITLE
Entered search terms and expressions are shown to be auto-corrected before searching works, but the original input is used correctly.

### ISSUE THREAD

**Issue by koenbokern** [dataesr/works-magnet#73]
Entered search terms and expressions are shown to be auto-corrected before searching works, but the original input is used correctly.

For example:
- entering 'aeres' shows 'aires' before searching works
- entering 'avans' shows 'advances' before searching works

**Comment by koenbokern** [comment]
Excuse me, auto-translation French to English was turned on, while not being needed.

**Comment by annelhote** [comment]
Hi @koenbokern , if you think that it is not an issue for the works-magnet, may I let you close the issue ? Thank you
